### ISSUE TITLE
the z direction in 2D mateirlas

### ISSUE THREAD

**Issue by tron1989** [Z2PackDev/Z2Pack#40] opened 2016-09-14 17:07 UTC
Does the z direction in 2D materials will result in the error:
"No overlap matrices were found. Maybe switch from shell_list to search_shells in wannier90.win or add more k-points to the string."

for the the c direction is about 30 A, which make the system a thin unit cell?

**Comment by greschd** [comment] 2016-09-14 17:48
Yes, this can happen when the k-points in a neighbouring brillouin zone are closer than the next one along the line of k-points.

This will be fixed with the next Wannier90 version (current development version) because it will allow explicitly specifying the neighbours. (If you are using a code that works with Wannier90 2.0)


As for what you can do now to avoid this issue, there is a section in the tutorial: http://z2pack.ethz.ch/doc/2.0/tutorial_system.html#preparing-input-files

**Comment by tron1989** [comment] 2016-09-14 18:27
Thanks a lot. Unfortunately, I am using Vasp which is only compatible with wannier90 1.2.
I have noticed that  topological invariants Z2 and chern number fully realized in your code, and is there any idea to realize the calculation of the Mirror Chern Number?

As I know, the mirror chern number needs to classify the bands with two groups.
Is it a very difficult task to realize it?

**Comment by greschd** [comment] 2016-09-14 21:31
If you're using VASP you will just have to either use more k-points along the line or try if it works for some value of ``search_shells``.

As for the mirror Chern numbers, you have to split the bands into two groups according to their mirror eigenvalue. We have the code to do this from Quantum Espresso, but I don't know if it's easily possible from VASP. If you know the symmetry representation in the basis of the Wannier functions, it should also be possible to split the overlap matrix into the two groups -- but again, I haven't done this yet.

The next version of Wannier90 should also allow for getting the symmetry representations, and I'll see if I can implement a generic algorithm to split by symmetry from there.

**Comment by tron1989** [comment] 2016-09-15 10:03
Just now, I have tested my calculations, the error happended for vasp:

> 
>     Your generating k-point grid is not commensurate to the symmetry       |
> |      of the lattice.  This does not sit well in combination with the        |
> |      PEAD routines, sorry ...                                               |
> |      suggested SOLUTIONS:                                                   |
> |       ) if not already the case, use automatic k-point generation           |
> |       ) shift your grid to Gamma (G) (e.g. required for hex or fcc lattice) 


IT seems that the KPOINTS generated by the code itself is not suitable, Here is the kpoints:

> > Automatic mesh
> 0              ! number of k-points = 0 ->automatic generation scheme
> Gamma          ! generate a Gamma centered grid
> 8 1 1         ! subdivisions
> 0.0 0.05 0.0          ! shift

my system is 2d SYSTEM .

**Comment by greschd** [comment] 2016-09-15 10:10
Is this the same run that you had before? The error message before would mean that VASP actually ran without problems. 
In general, you have to set ``ISYM = -1`` (switch off symmetry), maybe this is the cause for the error.

**Comment by tron1989** [comment] 2016-09-15 10:14
In fact, this is the same run as before. The problem before seems sovled when I comment the NPAR  (which is of course not suitable with wannier90,), the ISYM is set to be 0, which is also to switch off symmetry.

**Comment by greschd** [comment] 2016-09-15 10:19
Can you try setting it to ``ISYM=-1``? According to the VASP docs, ``ISYM=0`` still uses symmetry to reduce the sampling. Maybe this is what produces the problem. 
As for ``NPAR``, this shouldn't be a problem -- it's just that Wannier90 itself runs serial. You just have to be careful that the number of bands is a multiple of ``NPAR``, because otherwise VASP will automatically add bands, and then the ``exclude_bands`` parameter in the wannier90 input is wrong.

**Comment by tron1989** [comment] 2016-09-15 10:31
It seems that there is sth wrong with my compile version Vasp with wannier90. The problem always happend when I set the wannier90 in Vasp. Reconsidering the calculations in the past, when NPAR is set,  the nscf calculation is normal, but when it begin to generate the wannier90 files, it stopped for some error similiar as  the memory.

**Comment by greschd** [comment] 2016-09-15 10:43
Indeed, this could be a problem just with your VASP  compilation. I guess unless the performance is really bad you can use it without ``NPAR``.

Does the error about the k-point grid still appear with ``ISYM = -1``.

**Comment by tron1989** [comment] 2016-09-15 11:08
Yeah, there is some problem with my conpilation.

The new calcutaion with ISYM=-1 is submitted to be waited for calculation.

**Comment by tron1989** [comment] 2016-09-16 06:50
Dear greschd,

The calculation with ISYM=-1 is normal! Thank you very much.
There is another question. I have checked your codes, It support the wannier90_hr.dat, and in the tbmodels.Model.from_hr_file or tbmodels.Model.from_hr, how can set the parameters such as occupied bands like in z2pack.hm.System?

**Comment by greschd** [comment] 2016-09-16 07:34
You can give the same parameters as for ``hm.System``. Under the covers, the tight-binding implementation uses the ``hm.System``, and the keyword arguments are just passed on.

**Closed** 2016-09-16 07:40 UTC

**Comment by ahzeeshan** [comment] 2018-05-12 18:55
I have a related question. I was running the same calculation on a surface with length ~3 Angstroms along x and y and 30 Angstroms in the z-direction to avoid interaction between periodic images using quantum espresso with Z2pack. The default settings in Bi_qe example didn't work, so I removed shell_list=1 and added search_shell parameter. Only at `search_shell=50` did the calculation run successfully. The documentation says about the `search_shell` parameter: `It should be large enough s.t. the direct neighbours are included, but not so large that the neighbour’s equivalent points are included.` Could you give me some intuition if my `search_shell` value of 50 is okay or not?

**Comment by greschd** [comment] 2018-05-13 21:36
Using the ``search_shells`` is really just a workaround, since there was no good way to specify which overlaps to compute in older Wannier90 versions. 

If you're using QE >= 6, you can use Wannier90 2.1 which can explicitly set which overlaps to compute. You can find the corresponding example here: https://github.com/Z2PackDev/Z2Pack/tree/dev/current/examples/fp/espresso/6/Bi
