### ISSUE TITLE
Error when calculating the Chern invariant from Wannier90-output tight-binding model

### ISSUE THREAD

**Issue by djstaros** [Z2PackDev/Z2Pack#149] opened 2023-03-01 20:08 UTC
Hello all,

I am trying to calculate the Chern invariant for a bilayer of interest. I previously ran a noncollinear Quantum Espresso --> Wannier90 workflow manually, so I am trying to calculate the invariant from the hr.dat and wsvec.dat output files I already have (attached). 

I am attempting to do so using the following code: 

#!/usr/bin/env python
import os
import sys
import z2pack
import tbmodels
model = tbmodels.Model.from_wannier_files(
    hr_file='bl_soc_2_hr.dat',
    wsvec_file='bl_soc_2_wsvec.dat'
)
system = z2pack.tb.System(model)
res = z2pack.surface.run(
    system=system,
    surface=z2pack.shape.Sphere(
        center=(0.3565, 0, 0), radius=0.003
    ),
)
print('Chern number:', z2pack.invariant.chern(res))`

which yields the following output and error:

+----------------------------------------------------------------------+
|   ===================                                                |
|   SURFACE CALCULATION                                                |
|   ===================                                                |
|   starting at 2023-03-01 14:55:26,337                             |
|   running Z2Pack version 2.2.0                                       |
|                                                                      |
|   gap_tol:            0.3                                            |
|   init_result:        None                                           |
|   iterator:           range(8, 27, 2)                                |
|   load:               False                                          |
|   load_quiet:         True                                           |
|   min_neighbour_dist: 0.01                                           |
|   move_tol:           0.3                                            |
|   num_lines:          11                                             |
|   pos_tol:            0.01                                           |
|   save_file:          None                                           |
|   serializer:         auto                                           |
|   surface:            Sphere((0.3565, 0, 0), 0.003)                  |
|   system:             <z2pack.tb.System object at 0x7fd535ea42e0>    |
+----------------------------------------------------------------------+

INFO: Adding lines required by 'num_lines'.
INFO: Adding line at t = 0.0
INFO:       Calculating line for N = 8
INFO:       Calculating line for N = 10
python(78108,0x7ff84adb54c0) malloc: Incorrect checksum for freed object 0x7fd535c3e710: probably modified after being freed.
Corrupt value: 0x3ff0000000000000
python(78108,0x7ff84adb54c0) malloc: *** set a breakpoint in malloc_error_break to debug
zsh: abort      python chern_attempt2.py

This only happens at some values of x for center=(x, 0, 0), but not for others. Why might this be happening? Thanks!

Best regards,
Daniel Staros

[files.zip](https://github.com/Z2PackDev/Z2Pack/files/10865896/files.zip)

**Comment by greschd** [comment] 2023-03-01 20:19
Hi Daniel,

Huh, this looks like an interesting error. Since there's no Python traceback, it probably comes from an extension module (something written in a compiled language), e.g. `numpy` or `scipy`.

Can you try running the code with `python -X dev`? That should hopefully generate more debug output.

> from the hr.dat and wsvec.dat output files I already have (attached)

Hm, those don't seem to be here. Maybe Github didn't accept the file types? As far as I can remember, `.zip` or `.tar.gz` should work.

Best regards,
Dominik

**Comment by djstaros** [comment] 2023-03-01 22:53
Dear Dominik,

Thank you for the suggestion. I have re-uploaded the files as "files.zip" in the original issue post. I also tried your suggestion, and it yields the following:

<frozen importlib._bootstrap>:219: ImportWarning: can't resolve package from __spec__ or __package__, falling back on __name__ and __path__

+----------------------------------------------------------------------+
|   ===================                                                |
|   SURFACE CALCULATION                                                |
|   ===================                                                |
|   starting at 2023-03-01 17:49:59,101                                |
|   running Z2Pack version 2.2.0                                       |
|                                                                      |
|   gap_tol:            0.3                                            |
|   init_result:        None                                           |
|   iterator:           range(8, 27, 2)                                |
|   load:               False                                          |
|   load_quiet:         True                                           |
|   min_neighbour_dist: 0.01                                           |
|   move_tol:           0.3                                            |
|   num_lines:          11                                             |
|   pos_tol:            0.01                                           |
|   save_file:          None                                           |
|   serializer:         auto                                           |
|   surface:            Sphere((0.3565, 0, 0), 0.003)                  |
|   system:             <z2pack.tb.System object at 0x7fe5a87be6e0>    |
+----------------------------------------------------------------------+

INFO: Adding lines required by 'num_lines'.
INFO: Adding line at t = 0.0
INFO:       Calculating line for N = 8
INFO:       Calculating line for N = 10
python(80734,0x7ff84adb54c0) malloc: Incorrect checksum for freed object 0x7fe5a812c7c0: probably modified after being freed.
Corrupt value: 0x3ff0000000000000
python(80734,0x7ff84adb54c0) malloc: *** set a breakpoint in malloc_error_break to debug
Fatal Python error: Aborted

Current thread 0x00007ff84adb54c0 (most recent call first):
  File "/Users/danielstaros/.local/lib/python3.8/site-packages/z2pack/surface/_run.py", line 223 in update_result
  File "/Users/danielstaros/.local/lib/python3.8/site-packages/z2pack/surface/_run.py", line 209 in add_line
  File "/Users/danielstaros/.local/lib/python3.8/site-packages/z2pack/surface/_run.py", line 269 in _run_surface_impl
  File "/usr/local/anaconda3/lib/python3.8/contextlib.py", line 75 in inner
  File "/Users/danielstaros/.local/lib/python3.8/site-packages/z2pack/surface/_run.py", line 123 in run_surface
  File "/Users/danielstaros/.local/lib/python3.8/site-packages/z2pack/_run_utils.py", line 21 in inner
  File "<decorator-gen-18>", line 2 in run_surface
  File "chern_attempt2.py", line 23 in <module>
zsh: abort      python -X dev chern_attempt2.py

Best regards,
Daniel Staros

**Comment by greschd** [comment] 2023-03-01 23:28
Ok, so at least it's telling us where the error occurs. If I'm reading this right, the offending line [1] is here:

https://github.com/Z2PackDev/Z2Pack/blob/39cd4565ed77c67062969056e52e8d9f652fff11/src/z2pack/surface/_run.py#L211

Which is code related to storing the data. Since you haven't configured any `save_file`, as far as I can the `send` call shouldn't do anything. The code for that is here:

https://github.com/Z2PackDev/Z2Pack/blob/39cd4565ed77c67062969056e52e8d9f652fff11/src/z2pack/_async_handler.py#L54-L56

So I wonder if something is going wrong in `copy.deepcopy`. If you don't mind installing from source, could you check what happens when you replace 

https://github.com/Z2PackDev/Z2Pack/blob/39cd4565ed77c67062969056e52e8d9f652fff11/src/z2pack/surface/_run.py#L211

by only 
```python
copy.deepcopy(result)
```
and/or completely remove it?

Unfortunately, I can't seem to reproduce the issue on my machine. So, to help narrow it down:
- Which OS are you running on?
- Is it a default Python, or a different one (e.g. conda)?
- Could you post the result of `pip freeze`?

If you have another Python (kind, or version) available, it's also worth checking if that behaves the same.

[1] translating the line number to the current `main` branch

**Comment by djstaros** [comment] 2023-03-02 15:19
Dominik,

I took your suggestion, and it did not seem to fix my problem completely; I didn't get the error right away, but if I make the sphere larger by a factor of 10, I can still reproduce the same error. By the way, I am running this on my personal laptop which runs MacOS Ventura. 

In the process, however, I noticed that my default "python" was Anaconda at "/usr/local/anaconda3/bin/python" whereas my default python3 was not Anaconda (/usr/local/bin/python3). By changing the shebang to instead say "#!/usr/bin/env python3", it seems I have resolved the issue. I guess Anaconda may have been trying to access memory to which it doesn't have access.

Thank you very much for the help!

**Comment by greschd** [comment] 2023-03-03 08:23
That's great to hear! I _suspect_ there's a binary incompatibility between packages installed through conda (or the interpreter itself), and packages installed via `pip`. I'm not all that familiar with conda however, this is only speculation.

If you want to go back to using Z2Pack via conda, you could try either installing all the binary dependencies via conda, and only Z2Pack + TBmodels (which are pure-Python) with pip, or having everything built from source when pip-installing with the `--no-binary :all:` flag to `pip install`.

I'll close the issue for now, feel free to re-open if you need more help.

**Closed by greschd** 2023-03-03 08:23 UTC
