### ISSUE TITLE
System with non-orthogonal basis / Z2Pack on top of Siesta

### ISSUE THREAD

**Issue by juijan** [Z2PackDev/Z2Pack#79] opened 2019-08-27 08:38 UTC
Hey,

I was wondering whether there is a physical reason, why the tight-binding and especially hamilton matrix interfaces only consider orthogonal basis sets. If not do, you believe, that the changes to hm.py (attached) that I have made would be reasonable?

My motivation: I would like to use Z2Pack ontop of SIESTA. SIESTA used localise pseudo-atomic orbitals as the basis set, i.e. the hamiltonian and overlap matrix can be retrieved in a tight-binding-like form and for example read with the [sisl](https://github.com/zerothi/sisl) package, which also provides interfaces for overlap and Hamiltonian at any k.

I have also been working on extending the functionality of SIESTA to produce wannier90-type .mmn not only for calculations with collinear to non-collinear spins. 

Hence, if the above worked it would be a good tool to test.

Thank you for your time.

[hm_with_overlap.patch.txt](https://github.com/Z2PackDev/Z2Pack/files/3545085/hm_with_overlap.patch.txt)

**Comment by greschd** [comment] 2019-09-04 06:00
I don't see a reason why this shouldn't work - seems like a reasonable extension for the code. Please let me know if the test with SIESTA worked as expected.

If we can get a good example and / or test for this functionality, it would be good to merge it into the repository. Please let me know if you are up for creating the corresponding pull request.

**Comment by bfocassio** [comment] 2020-04-08 20:31
To test if the sisl Hamiltonians could be used along with z2pack, I tried the Haldane model and Kane-Mele model, written with sisl language, and using Z2pack to compute the Chern number and Z2 invariant, respectively. Everything seems to be working properly. Both examples are attached.
  
I performed the changes proposed in the issue, and tested it with flat bismuthene computed with SIESTA. The necessary files to run the Z2 calculation are attached.

The problem is that I'm finding it very hard to converge the calculations and get reliable results. The calculation is very sensitive to the 'pos_tol' that needs to be increased at least to 0.05, and it gets worse with increasing the number of lines. Any help is appreciated.

[siesta_sisl_z2pack.zip](https://github.com/Z2PackDev/Z2Pack/files/4452656/siesta_sisl_z2pack.zip)

**Comment by greschd** [comment] 2020-04-09 11:33
This problem might be unrelated to the SIESTA implementation - it looks suspiciously like there was a gap closure around ky ~= 0.3. When the direct band gap vanishes anywhere on the surface to be considered, the Z2 invariant becomes ill-defined.

Could you check if this might be the case?

**Comment by bfocassio** [comment] 2020-04-09 15:34
The gap does not seem to close anywhere in the BZ.

![Figure_1](https://user-images.githubusercontent.com/23397880/78912835-73690b80-7a5e-11ea-8994-0ca7e470fa1b.png)

**Comment by greschd** [comment] 2020-04-09 16:03
[Note that I didn't try running the code yet, only looked at the output in the Notebook]

From this figure it seems there are 4 occupied bands, whereas in the notebook `len(occupied)` is 12 - maybe this is the source of these problems?

**Comment by bfocassio** [comment] 2020-04-09 17:01
[I updated the zip because I was using the development version of sisl. Now the code should run with the latest release version, 0.9.8.]

In the image a chose to show only some bands. There is  a total of 12 occupied bands.

**Comment by greschd** [comment] 2020-04-09 17:10
Ah, I see - so the other occupied bands are below the ones shown here?

I'll have to give this a closer look to see what might be going wrong. Probably [this](https://github.com/Z2PackDev/Z2Pack/blob/dev/current/z2pack/line/_data.py#L136) is another place where orthonormality is assumed, and the overlap would need to be taken into account.

**Comment by juijan** [comment] 2020-04-10 07:04
Indeed, the overlap would have to be taken into account there as well. 

I don't see a way of calculating the overlap between two wavefunctions at different k using only the overlap matrix and Hamiltonian matrix. I believe one would also require the matrix elements of e^{ikr}.

Unfortunately, I did not find time recently to finalize the implementation of the Wannier90 modules for spin-orbit coupling in SIESTA either.

**Comment by bfocassio** [comment] 2020-04-29 22:07
I think this could be solved by applying the Löwdin transformation, at each k point. With this we get a Hamiltonian in an orthogonal basis.

At each k we have **H** and **S**,

We compute the eigenvalues **s** and eigenvectors **U** of the overlap matrix, as **SU** = **sU**

Then, we compute s^(-1/2) for each s in **s**, write it as a diagonal matrix **s**^(-1/2)

Now, transform back to the **S** basis with **S**^(-1/2) = **U** **s**^(-1/2) **U**^(dagger)

And finally compute **H'** = **S**^(-1/2) **H** **S**^(-1/2)

I performed some tests with 2 different systems and several lines. It seems to be stable and working fine. See the attached file for using this with bismuthene.

Let me know if this procedure is correct

[siesta_z2pack_bismuthene.zip](https://github.com/Z2PackDev/Z2Pack/files/4554940/siesta_z2pack_bismuthene.zip)

**Comment by greschd** [comment] 2020-07-23 22:24
Sorry for the late reply - yes, I think this is correct. I'll note how I think about this below, so you can confirm we have the same understanding. It's basically just the derivation of the Loewdin transformation:

Assume **B** is the matrix containing the non-orthogonal basis vectors as column vectors, with respect to some (arbitrary) orthonormal basis.

**S = B^(\dagger) B**

We can do singular value decomposition on **B**:

**B = V \Sigma W^(\dagger)**

**S = W \Sigma^2 W^(\dagger)**

**S^(-1/2) = W \Sigma^(-1) W^(\dagger)**

If **H_0** is the Hamiltonian w.r.t. the arbitrary orthonormal basis above,

**H = B^(\dagger) H_0 B**

**H' = S^(-1/2) H S^(-1/2) =**
**= W \Sigma^(-1) W^(\dagger) B^(\dagger) H_0 B W \Sigma^(-1) W^(\dagger) =**
**= W V^(\dagger) H_0 V W^(\dagger)**

which is exactly what we want, the Hamiltonian w.r.t a new orthonormal basis.

In principle, this can be used without modifying the Z2Pack code by simply providing **H'** instead of **H** and **S**, correct? Of course, it might pay to include it in the code instead of everyone having to figure it out by themselves.

**Comment by bfocassio** [comment] 2020-07-25 15:55
Yes, that's correct.

Currently I'm calculating **H'** then passing it to Z2Pack. It would be nice have this implemented within Z2Pack. I can look into this.

**Comment by greschd** [comment] 2020-07-27 15:44
> 
> Currently I'm calculating **H'** then passing it to Z2Pack. It would be nice have this implemented within Z2Pack. I can look into this.

Would be much appreciated! Thinking about it some more, I now think adding it directly to `z2pack.hm.System` might actually be the best idea. Otherwise the class hierarchy becomes a bit complicated, and it would be cumbersome to e.g. add it to `z2pack.tb`.

So it'd probably amount to adding a `basis_overlaps` keyword (default `None`) to that class, and add a property `_hamilton_orthogonal` that either directly calls the `_hamilton` or performs the orthogonalization.

Regarding the procedure itself: When the **s** entries approach zero this becomes numerically unstable - but I guess at that point the basis is also bad for other parts of the calculation, right?

**Comment by greschd** [comment] 2020-09-18 08:32
This was merged in #94 (thanks again @bfocassio and @juijan) and released in the 2.2.0 version.

It would be good to add some tests, but I added a separate issue for that (#95).

**Closed by greschd** 2020-09-18 08:32 UTC
